#!/usr/bin/env python3
"""Regenerate the AVR frame header from the master frame data.

Single source of truth is c/meow_frames.h. This decodes its RLE grayscale
frames, picks CAT_NF frames spread evenly along cumulative MOTION (not by
index -- several of the 45 frames are near-duplicate held frames, and
index-even sampling lands on them and the spin looks stuck), downsamples to
CAT_D x CAT_D, thresholds to 1 bit, and emits a header that stores the data
in flash on AVR (PROGMEM) and normally everywhere else.

    python3 avr/gen_catmin_avr.py

Run this whenever c/meow_frames.h changes; deploy.sh does it automatically.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "c", "meow_frames.h")
OUT = os.path.join(HERE, "meow_micro", "catmin_avr.h")

SIZE, NFRAMES = 110, 45
INK = 2          # frame level >= this counts as ink (keeps thin lines)
D = 48           # output grid, D x D
NF = 8           # frames kept


def read_array(text, name):
    m = re.search(r"%s\[\d+\]\s*=\s*\{(.*?)\};" % re.escape(name), text, re.S)
    if not m:
        sys.exit("gen_catmin_avr: array %s not found in %s" % (name, SRC))
    return [int(x) for x in re.findall(r"-?\d+", m.group(1))]


def main():
    with open(SRC) as fh:
        text = fh.read()
    value = read_array(text, "meow_rle_value")
    count = read_array(text, "meow_rle_count")
    offset = read_array(text, "meow_frame_off")
    duration = read_array(text, "meow_duration_ms")

    # RLE -> full grayscale frames
    frames = []
    for f in range(NFRAMES):
        buf = bytearray()
        for r in range(offset[f], offset[f + 1]):
            buf += bytes([value[r]]) * count[r]
        frames.append(buf)

    def silhouette(frame):
        out = bytearray(D * D)
        for y in range(D):
            sy = y * SIZE // D
            for x in range(D):
                out[y * D + x] = 1 if frame[sy * SIZE + x * SIZE // D] >= INK else 0
        return out

    sils = [silhouette(f) for f in frames]

    def distance(a, b):
        return sum(1 for p, q in zip(a, b) if p != q)

    # cumulative motion around the cycle, then sample it evenly
    arc = [0]
    for i in range(NFRAMES):
        arc.append(arc[-1] + distance(sils[i], sils[(i + 1) % NFRAMES]))
    total = arc[-1]

    picked = []
    for k in range(NF):
        target = k * total / NF
        j = 0
        while j < NFRAMES and arc[j + 1] < target:
            j += 1
        while j in picked:
            j = (j + 1) % NFRAMES
        picked.append(j)

    def pack(frame):
        out = bytearray((D * D + 7) // 8)
        for y in range(D):
            sy = y * SIZE // D
            for x in range(D):
                if frame[sy * SIZE + x * SIZE // D] >= INK:
                    i = y * D + x
                    out[i >> 3] |= 1 << (7 - (i & 7))
        return out

    blob = b"".join(pack(frames[k]) for k in picked)
    times = [max(90, duration[k]) for k in picked]
    per_frame = (D * D + 7) // 8

    lines = [
        "/* Generated by avr/gen_catmin_avr.py -- do not edit by hand.",
        " * Source of truth: c/meow_frames.h",
        " * %d frames of %dx%d, 1 bit per pixel, %d bytes total."
        % (NF, D, D, len(blob)),
        " * Frames picked by even MOTION spacing: %s" % (picked,),
        " */",
        "#ifndef CATMIN_AVR_H",
        "#define CATMIN_AVR_H",
        "",
        "/* On AVR the data must stay in flash: %d bytes cannot fit the" % len(blob),
        " * ATmega32U4's 2560 bytes of SRAM. Elsewhere it is a normal array. */",
        "#ifdef __AVR__",
        "#  include <avr/pgmspace.h>",
        "#  define CAT_STORE PROGMEM",
        "#  define CAT_RD_BYTE(p) pgm_read_byte(p)",
        "#  define CAT_RD_WORD(p) pgm_read_word(p)",
        "#else",
        "#  define CAT_STORE",
        "#  define CAT_RD_BYTE(p) (*(p))",
        "#  define CAT_RD_WORD(p) (*(p))",
        "#endif",
        "",
        "#define CAT_D %d" % D,
        "#define CAT_NF %d" % NF,
        "#define CAT_BPF %d" % per_frame,
        "",
        "static const unsigned char cat_bits[%d] CAT_STORE = {" % len(blob),
    ]
    for i in range(0, len(blob), 24):
        lines.append("  " + ",".join(str(b) for b in blob[i:i + 24]) + ",")
    lines += [
        "};",
        "",
        "static const unsigned int cat_ms[%d] CAT_STORE = {%s};"
        % (NF, ",".join(str(t) for t in times)),
        "",
        "#endif /* CATMIN_AVR_H */",
    ]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s (%d bytes of frame data, frames %s)" % (OUT, len(blob), picked))


if __name__ == "__main__":
    main()
